# Generated by Django 2.2.3 on 2019-07-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_auto_20190704_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionuserprofile',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
