# Generated by Django 2.2.3 on 2019-07-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_auto_20190704_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('connection_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'connection',
                'verbose_name_plural': 'connections',
            },
        ),
        migrations.AlterModelOptions(
            name='connectionuserprofile',
            options={'verbose_name': 'connection Profile', 'verbose_name_plural': 'connection Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userloginactivity',
            options={'verbose_name': 'user Activity', 'verbose_name_plural': 'user Activities'},
        ),
    ]
