# Generated by Django 2.2.3 on 2019-07-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_auto_20190704_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionuserprofile',
            options={'verbose_name': 'connection User Profile', 'verbose_name_plural': 'connection User Profiles'},
        ),
    ]
